# Generated by Django 3.0.3 on 2021-01-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210131_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Brans_products', to='store.Brand'),
        ),
    ]
