# Generated by Django 3.0.3 on 2021-01-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210131_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Cost_to_customer',
            field=models.PositiveIntegerField(help_text='Price that customer will PAY!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost_to_seller',
            field=models.PositiveIntegerField(help_text='Total Cost of product for seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Crossed_price',
            field=models.PositiveIntegerField(help_text='Price that will be crossed'),
        ),
    ]
