# Generated by Django 3.0.3 on 2021-02-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210206_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Variant',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='Cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='store.Cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartvariant',
            name='Cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Variant', to='store.Cart'),
            preserve_default=False,
        ),
    ]
