# Generated by Django 3.0.3 on 2021-02-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210207_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cartproduct', to='store.Cart'),
        ),
        migrations.AlterField(
            model_name='cartvariant',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cartvariant', to='store.Cart'),
        ),
    ]
