# Generated by Django 3.0.3 on 2021-02-07 18:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210207_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='AttrCache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=store.models.return_dict),
        ),
    ]
