# Generated by Django 3.0.3 on 2021-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_variant_attrcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Discount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
