# Generated by Django 3.0.3 on 2021-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210208_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='Discount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
