# Generated by Django 3.0.3 on 2021-02-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210208_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.PositiveSmallIntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Discount',
            field=models.PositiveSmallIntegerField(blank=True, editable=False),
        ),
    ]
