# Generated by Django 3.0.3 on 2021-02-10 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210210_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Block',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='Address',
            field=models.TextField(default='Not Given', help_text='Area Name and Gali/Street Number', max_length=720),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='AddressType',
            field=models.CharField(choices=[('HOME', 'HOME (All day delivery)'), ('WORK', 'Work/Office (From 10AM To 5PM)')], help_text='HOME For All Day Delivery\nOFFICE For Delivery Between 9AM - 6PM', max_length=164),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='AltPhoneNumber',
            field=models.BigIntegerField(help_text='If First Phone Number Will Not Work, We Will Use This', validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Alternate(Second) Phone No'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='District',
            field=models.CharField(max_length=128, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='LandMark',
            field=models.CharField(help_text='(Optional)\nEx-opposite SBI or near this building...', max_length=164),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='OwnerName',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='PIN',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000)], verbose_name='PIN Code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='PhoneNumber',
            field=models.BigIntegerField(help_text='Your Main Phone Number', validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Main Phone No'),
        ),
    ]
