# Generated by Django 3.0.3 on 2021-02-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210210_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='AddressType',
            field=models.CharField(choices=[('HOME', 'HOME (All day delivery)'), ('WORK', 'Work/Office (From 10AM To 5PM)')], max_length=164),
        ),
    ]
