# Generated by Django 3.0.3 on 2021-02-10 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210210_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='AddressType',
            field=models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'Work/Office')], default='HOME', help_text='HOME : For All Day Delivery <br> OFFICE : For Delivery Between 9AM - 6PM', max_length=164),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='AltPhoneNumber',
            field=models.BigIntegerField(help_text='If First Phone Number Will Not Work, We Will Use This', validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Alternate [ Second ] Phone Number'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='PhoneNumber',
            field=models.BigIntegerField(help_text='Your Main Phone Number', validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Main Phone Number'),
        ),
    ]
