# Generated by Django 3.0.3 on 2021-02-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210210_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='PIN',
            field=models.PositiveSmallIntegerField(verbose_name='PIN Code'),
        ),
    ]
