# Generated by Django 3.0.3 on 2021-02-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210210_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='PIN',
            field=models.PositiveIntegerField(verbose_name='PIN Code'),
        ),
    ]
