# Generated by Django 3.0.3 on 2021-02-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210210_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Gender',
        ),
    ]
