# Generated by Django 3.0.3 on 2021-02-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ProfilePic',
        ),
    ]
