# Generated by Django 3.0.3 on 2021-02-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cart',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='store.Cart'),
        ),
    ]
