# Generated by Django 3.0.3 on 2021-02-13 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210211_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='Created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
