# Generated by Django 3.0.3 on 2021-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210213_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='CodeWord',
            field=models.CharField(default='t', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
