# Generated by Django 3.0.3 on 2021-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_paymentmethod_codeword'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
    ]
