# Generated by Django 3.0.3 on 2021-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar_images',
            name='GotoUrl',
            field=models.URLField(default='http://127.0.0.1:8000/handle_product_search/?page=2&productquery=pen'),
            preserve_default=False,
        ),
    ]
