# Generated by Django 3.0.3 on 2021-02-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_topbar_images_gotourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide_mob',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='slide_mob',
            name='Variant',
        ),
        migrations.RemoveField(
            model_name='slide_pc',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='slide_pc',
            name='Variant',
        ),
    ]
