# Generated by Django 3.0.3 on 2021-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210213_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='All_products',
            new_name='Products',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='All_products_with_variants',
        ),
        migrations.AddField(
            model_name='collection',
            name='Variants',
            field=models.ManyToManyField(blank=True, related_name='In_collection', to='store.Variant'),
        ),
    ]
