# Generated by Django 3.0.3 on 2021-02-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210213_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorey',
            options={'verbose_name': 'Categorey', 'verbose_name_plural': 'Categorey'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Product Feature Name', 'verbose_name_plural': 'Product Feature Name'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Product Feature Value', 'verbose_name_plural': 'Product Feature Value'},
        ),
        migrations.AlterModelOptions(
            name='subcategorey',
            options={'verbose_name': 'Sub-Categorey', 'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AddField(
            model_name='categorey',
            name='Show_on_mainpage',
            field=models.BooleanField(default=False),
        ),
    ]
