# Generated by Django 3.0.3 on 2021-02-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210214_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Package and Bundle', 'verbose_name_plural': 'Packages and Bundles'},
        ),
        migrations.AddField(
            model_name='collection',
            name='Show_on_mainpage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=128)),
                ('ImageText', models.CharField(default='', editable=False, max_length=128)),
                ('Description', models.TextField(max_length=256)),
                ('Poster', models.ImageField(blank=True, upload_to='Product_row/posters')),
                ('Show_on_mainpage', models.BooleanField(default=False)),
                ('Products', models.ManyToManyField(blank=True, related_name='In_row', to='store.Product')),
                ('Variants', models.ManyToManyField(blank=True, related_name='In_row', to='store.Variant')),
            ],
            options={
                'verbose_name': 'Product Slider',
            },
        ),
    ]
