# Generated by Django 3.0.3 on 2021-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210214_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Main Slider'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='Name',
            field=models.CharField(max_length=128, verbose_name='Tittle'),
        ),
        migrations.AlterField(
            model_name='productrow',
            name='Name',
            field=models.CharField(max_length=128, verbose_name='Tittle'),
        ),
    ]
