# Generated by Django 3.0.3 on 2021-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20210214_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Categorey',
        ),
        migrations.AddField(
            model_name='product',
            name='Categorey',
            field=models.ManyToManyField(related_name='All_products', to='store.SubCategorey'),
        ),
        migrations.RemoveField(
            model_name='productwithvariant',
            name='Categorey',
        ),
        migrations.AddField(
            model_name='productwithvariant',
            name='Categorey',
            field=models.ManyToManyField(related_name='All_products_with_variant', to='store.SubCategorey'),
        ),
    ]
