# Generated by Django 3.0.3 on 2021-02-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20210215_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=64)),
                ('Description', models.TextField(max_length=164)),
                ('Link', models.URLField()),
                ('BackgroundImage', models.ImageField(upload_to='banner')),
                ('Active', models.BooleanField(default=False)),
                ('Type', models.CharField(choices=[('0', 'left'), ('1', 'center'), ('2', 'right')], default='normal', max_length=64)),
            ],
        ),
    ]
