# Generated by Django 3.0.3 on 2021-02-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
