# Generated by Django 3.0.3 on 2021-02-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20210215_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Categories',
            field=models.ManyToManyField(blank=True, editable=False, related_name='In_orders', to='store.Categorey'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('0', 'Placed'), ('1', 'Order Recived'), ('2', 'Declined By Seller'), ('3', 'Cancelation Requested'), ('4', 'Cancel Completed'), ('5', 'Packed & Bill Genrated'), ('6', 'Shipped Out'), ('7', 'On The Way'), ('8', 'Completed'), ('9', 'Declined By Buyer'), ('10', 'Return Requested'), ('11', 'Return Completed'), ('12', 'Disputed'), ('13', 'Verification Required')], default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='SubCategories',
            field=models.ManyToManyField(blank=True, editable=False, related_name='In_orders', to='store.SubCategorey'),
        ),
    ]
