# Generated by Django 3.0.3 on 2021-02-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20210216_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CurrentShippingAddress',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.PROTECT, related_name='AddressCustomer', to='store.ShippingAddress'),
            preserve_default=False,
        ),
    ]
