# Generated by Django 3.0.3 on 2021-02-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20210216_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CurrentShippingAddress',
        ),
        migrations.AlterField(
            model_name='order',
            name='Method',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders', to='store.PaymentMethod'),
        ),
    ]
