# Generated by Django 3.0.3 on 2021-02-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20210216_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders', to='store.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ShippingAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Orders', to='store.ShippingAddress'),
        ),
    ]
