# Generated by Django 3.0.3 on 2021-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20210218_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=126)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Subject', models.CharField(max_length=164)),
                ('Message', models.TextField(max_length=700)),
            ],
        ),
    ]
