# Generated by Django 3.0.3 on 2021-02-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='PhoneNumber',
            field=models.CharField(max_length=124),
        ),
    ]
