# Generated by Django 3.0.3 on 2021-01-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='products/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Images',
        ),
    ]
