# Generated by Django 3.0.3 on 2021-01-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210111_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='slider/images')),
                ('Related_slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='store.Slider')),
            ],
        ),
    ]
