# Generated by Django 3.0.3 on 2021-01-12 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210112_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Added_by',
            field=models.CharField(blank=True, default='Rohit admin', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cart_probablity',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost_to_customer',
            field=models.PositiveIntegerField(default='625'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost_to_seller',
            field=models.PositiveIntegerField(default='625'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Crossed_price',
            field=models.PositiveIntegerField(default='700'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Local_offer',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Nums_of_rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sales_probablity',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='products/thumbnails'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_carts',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_sales',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
