# Generated by Django 3.0.3 on 2021-01-12 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210112_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Cart_probablity',
            field=models.FloatField(blank=True, default=1, editable=False, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Nums_of_rating',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Rating',
            field=models.FloatField(editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sales_probablity',
            field=models.FloatField(blank=True, default=1, editable=False, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Thumbnail',
            field=models.ImageField(blank=True, default='no image', upload_to='products/thumbnails'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_carts',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_sales',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_views',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
