# Generated by Django 3.0.3 on 2021-01-12 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210112_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Rating',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
