# Generated by Django 3.0.3 on 2021-01-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210112_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='Related_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Its_images', to='store.Product'),
        ),
    ]
