# Generated by Django 3.0.3 on 2021-01-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_images_related_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Brans_products', to='store.Brand'),
        ),
    ]
