# Generated by Django 3.0.3 on 2021-01-15 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Remaining_stock',
            field=models.PositiveIntegerField(blank=True, default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Total_stock',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost_to_customer',
            field=models.PositiveIntegerField(default='625', help_text='Price that customer will PAY!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost_to_seller',
            field=models.PositiveIntegerField(default='625', help_text='Total Cost of product for seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Crossed_price',
            field=models.PositiveIntegerField(default='700', help_text='Price that will be crossed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Local_offer',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Discount percentage (%)', validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Thumbnail',
            field=models.ImageField(blank=True, default='no image', editable=False, upload_to='products/thumbnails'),
        ),
    ]
