# Generated by Django 3.0.3 on 2021-01-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210115_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeError', models.CharField(max_length=50)),
                ('Property', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Categorey',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Tags',
        ),
        migrations.AddField(
            model_name='product',
            name='Categorey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='All_products', to='store.Categorey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Added_by',
            field=models.CharField(blank=True, default='Rohit admin', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='Remaining_stock',
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
    ]
