# Generated by Django 3.0.3 on 2021-01-18 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210116_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='products/images/thumb'),
        ),
        migrations.AddField(
            model_name='tag',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_images',
            name='Images',
            field=models.ImageField(help_text='This will be the high quality image', upload_to='products/images/highres'),
        ),
    ]
