# Generated by Django 3.0.3 on 2021-01-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210119_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Property',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Type',
        ),
        migrations.AddField(
            model_name='variant',
            name='Image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='variants/images'),
        ),
        migrations.AddField(
            model_name='variant',
            name='Product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='Variant', to='store.Product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=50)),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Attributevalue', to='store.ProductAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='AttributeValue',
            field=models.ManyToManyField(related_name='VariantSet', to='store.ProductAttributeValue'),
        ),
    ]
