# Generated by Django 3.0.3 on 2021-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210120_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Remaining_stock',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
