# Generated by Django 3.0.3 on 2021-01-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210120_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Remaining_stock',
        ),
    ]
