# Generated by Django 3.0.3 on 2021-01-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_remaining_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='For_product_types',
            field=models.ManyToManyField(related_name='Valid_product_attributes', to='store.Product_type'),
        ),
    ]
