# Generated by Django 3.0.3 on 2021-01-20 10:38

import django.contrib.postgres.fields
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productattribute_for_product_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='For_product_types',
        ),
        migrations.AddField(
            model_name='product_type',
            name='Product_type_attributes',
            field=models.ManyToManyField(to='store.ProductAttribute'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Meta_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=store.models.return_array, size=None, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='Type'),
        ),
    ]
