# Generated by Django 3.0.3 on 2021-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210120_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='Product_type_attributes',
            field=models.ManyToManyField(related_name='Product_types', to='store.ProductAttribute'),
        ),
    ]
