# Generated by Django 3.0.3 on 2021-01-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210120_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorey',
            name='Parent_categorey',
        ),
        migrations.AddField(
            model_name='subcategorey',
            name='Parent_categorey',
            field=models.ManyToManyField(related_name='Subcategorey', to='store.Categorey', verbose_name='In Categorey Group'),
        ),
    ]
