# Generated by Django 3.0.3 on 2021-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210121_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='Title',
            field=models.CharField(default='', max_length=164),
            preserve_default=False,
        ),
    ]
