# Generated by Django 3.0.3 on 2021-01-21 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='Last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
