# Generated by Django 3.0.3 on 2021-01-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210121_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Product Attribute ( विशेषता )', 'verbose_name_plural': 'Product Attribute ( विशेषता )'},
        ),
    ]
