# Generated by Django 3.0.3 on 2021-01-22 13:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210122_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='AttributeValue',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Price',
        ),
        migrations.AddField(
            model_name='variant',
            name='Cost_to_customer',
            field=models.PositiveIntegerField(default='625', help_text='Price that customer will PAY!'),
        ),
        migrations.AddField(
            model_name='variant',
            name='Cost_to_seller',
            field=models.PositiveIntegerField(default='625', help_text='Total Cost of product for seller'),
        ),
        migrations.AddField(
            model_name='variant',
            name='Crossed_price',
            field=models.PositiveIntegerField(default='700', help_text='Price that will be crossed'),
        ),
        migrations.AddField(
            model_name='variant',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='Local_offer',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Discount percentage (%)', validators=[django.core.validators.MaxValueValidator(90)], verbose_name='Discount in ( % )'),
        ),
        migrations.AddField(
            model_name='variant',
            name='Name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Total_stock',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='Attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attributevalue', to='store.ProductAttribute'),
        ),
        migrations.CreateModel(
            name='ProductWithVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
                ('Name_list', models.CharField(max_length=1024)),
                ('Description', models.TextField()),
                ('Main_image', models.ImageField(upload_to='varianceproduct/mainimages')),
                ('Highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=164), default=store.models.return_array, size=None)),
                ('Meta_data', django.contrib.postgres.fields.jsonb.JSONField(default=store.models.return_dict)),
                ('Rating', models.FloatField(default=0, editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('Nums_of_rating', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Brand')),
                ('Categorey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='All_products_with_variant', to='store.SubCategorey')),
                ('Tags', models.ManyToManyField(related_name='All_products_with_variant', to='store.Tag')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='All_products_with_variant', to='store.Product_type')),
            ],
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attributevalue', to='store.ProductWithVariant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Variants', to='store.ProductWithVariant'),
        ),
    ]
