# Generated by Django 3.0.3 on 2021-01-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210122_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributevalue',
            old_name='Product',
            new_name='Variant',
        ),
    ]
