# Generated by Django 3.0.3 on 2021-01-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210122_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='All_products_with_variants',
            field=models.ManyToManyField(related_name='In_collection', to='store.ProductWithVariant'),
        ),
        migrations.AddField(
            model_name='collection',
            name='All_variants',
            field=models.ManyToManyField(related_name='In_collection', to='store.Variant'),
        ),
    ]
