# Generated by Django 3.0.3 on 2021-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_collection_all_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='All_products',
            field=models.ManyToManyField(blank=True, related_name='In_collection', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='All_products_with_variants',
            field=models.ManyToManyField(blank=True, related_name='In_collection', to='store.ProductWithVariant'),
        ),
    ]
