# Generated by Django 3.0.3 on 2021-01-23 15:01

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_subcategorey_show_on_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='slider/mob_images')),
                ('Related_slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Slide_mob', to='store.Slider')),
            ],
        ),
        migrations.CreateModel(
            name='Slide_pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='slider/pc_images')),
                ('Related_slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Slide_pc', to='store.Slider')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Thumbnail',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='thumb',
        ),
        migrations.AddField(
            model_name='categorey',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(default=' ', upload_to='Categorey/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorey',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(default=' ', upload_to='SubCategorey/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='brand/images', verbose_name='Brand Logo Image'),
        ),
        migrations.AlterField(
            model_name='topbar_images',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='genimages'),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
