# Generated by Django 3.0.3 on 2021-01-23 15:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20210123_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Brand_image_cover',
            field=imagekit.models.fields.ProcessedImageField(upload_to='brand/images'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand_image_fill',
            field=imagekit.models.fields.ProcessedImageField(upload_to='brand/images'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand_image_fit',
            field=imagekit.models.fields.ProcessedImageField(upload_to='brand/images'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand_image_smart',
            field=imagekit.models.fields.ProcessedImageField(upload_to='brand/images'),
        ),
    ]
