# Generated by Django 3.0.3 on 2021-01-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20210123_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Brand_image_fit',
            new_name='Brand_image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='Brand_image_cover',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='Brand_image_fill',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='Brand_image_smart',
        ),
    ]
