# Generated by Django 3.0.3 on 2021-01-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20210123_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='Mainimage',
            new_name='Main_image',
        ),
    ]
