# Generated by Django 3.0.3 on 2021-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20210124_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileshare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageFile', models.ImageField(upload_to='fileshare')),
            ],
        ),
    ]
