# Generated by Django 3.0.3 on 2021-01-27 12:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20210124_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, editable=False, upload_to='products/thumbnails/main_images'),
        ),
        migrations.AddField(
            model_name='product_images',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, editable=False, upload_to='products/images/thumnails/highres'),
        ),
        migrations.AddField(
            model_name='productwithvariant',
            name='Thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, editable=False, upload_to='varianceproduct/thumbnail/mainimages'),
        ),
        migrations.AddField(
            model_name='variant',
            name='Thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, editable=False, upload_to='variants/thumbnails/images'),
        ),
        migrations.AddField(
            model_name='variantimages',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, editable=False, upload_to='product/images/thumbnails/varinat'),
        ),
    ]
