# Generated by Django 3.0.3 on 2021-01-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20210127_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Thumbnail',
        ),
    ]
