# Generated by Django 3.0.3 on 2021-01-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_remove_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='thumb',
        ),
        migrations.AddField(
            model_name='product',
            name='Thumbnail_path',
            field=models.CharField(default=' ', max_length=164),
            preserve_default=False,
        ),
    ]
