# Generated by Django 3.0.3 on 2021-01-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20210128_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Thumb_path',
            field=models.CharField(blank=True, editable=False, max_length=364),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='Thumb_path',
            field=models.CharField(blank=True, editable=False, max_length=364),
        ),
        migrations.AlterField(
            model_name='productwithvariant',
            name='Thumb_path',
            field=models.CharField(blank=True, editable=False, max_length=364),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Thumb_path',
            field=models.CharField(blank=True, editable=False, max_length=364),
        ),
        migrations.AlterField(
            model_name='variantimages',
            name='Thumb_path',
            field=models.CharField(blank=True, editable=False, max_length=364),
        ),
    ]
