# Generated by Django 3.0.3 on 2021-01-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20210128_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='Main_image',
            field=models.ImageField(blank=True, default='no image', upload_to='variants/images'),
            preserve_default=False,
        ),
    ]
