# Generated by Django 3.0.3 on 2021-01-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20210129_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Is_variant_product',
        ),
        migrations.RemoveField(
            model_name='productwithvariant',
            name='Is_variant_product',
        ),
        migrations.AddField(
            model_name='product',
            name='Is_variant',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='productwithvariant',
            name='Is_variant',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='Is_normal_product',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='Is_variant',
            field=models.BooleanField(blank=True, default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Is_normal_product',
            field=models.BooleanField(blank=True, default=True, editable=False),
        ),
    ]
