# Generated by Django 3.0.3 on 2021-01-28 23:22

import django.contrib.postgres.fields
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20210129_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='Highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=164), default=store.models.return_array, size=None),
        ),
    ]
