# Generated by Django 3.0.3 on 2021-01-28 23:23

import django.contrib.postgres.fields
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_variant_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='Highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=164), blank=True, default=store.models.return_array, editable=False, size=None),
        ),
    ]
