# Generated by Django 3.0.3 on 2021-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20210129_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
