# Generated by Django 3.0.3 on 2021-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_topbar_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Active',
            field=models.BooleanField(default=False, verbose_name='Show on Main Page'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='Active',
            field=models.BooleanField(default=False, verbose_name='Show on Main Page'),
        ),
    ]
