# Generated by Django 3.0.3 on 2021-01-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_auto_20210129_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide_mob',
            name='ProductWithVariant',
        ),
        migrations.RemoveField(
            model_name='slide_pc',
            name='ProductWithVariant',
        ),
        migrations.AddField(
            model_name='slide_mob',
            name='Variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Slide_mob', to='store.Variant'),
        ),
        migrations.AddField(
            model_name='slide_pc',
            name='Variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Slide_pc', to='store.Variant'),
        ),
    ]
