# Generated by Django 3.0.3 on 2021-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_auto_20210129_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='SliderCount_mob',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='SliderCount_pc',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
