# Generated by Django 3.0.3 on 2021-01-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20210130_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='SliderCount_mob',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='SliderCount_pc',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False),
        ),
    ]
